### ISSUE TITLE
Adapt to Build 172 Database tables

### ISSUE THREAD

**Issue by YanX94** [rigE08/cs2-skins-website#1]
Hi there,

Nereziel just released a new version of his plugin which use a new database tables, it would be so great if you could update the template !

Big love,

Yan

**Comment by YanX94** [comment]
up

**Comment by rigE08** [comment]
@HeartX94 Hi, sorry, i was busy with other things. Hope this will be ok.

Keep in touch if something doesn't work.

Thanks!
